# -*- coding: utf-8 -*-
"""individuales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPLtE7rzkI-6SAfgkzidv7puAT0jAmcg
"""

def caracter_a_bits(caracter):
    # Verificar que el argumento es un carácter único
    if len(caracter) != 1:
        raise ValueError("El argumento debe ser una cadena de un solo carácter")

    # Obtener el valor Unicode del carácter
    valor_unicode = ord(caracter)

    # Convertir el valor Unicode a una cadena de bits de 8 bits
    bits_resultado = format(valor_unicode, '08b')

    return bits_resultado

# Ejemplo de uso
caracter = 'a'
bits_caracter = caracter_a_bits(caracter)
print(bits_caracter)  # Salida: '01100001'